openapi: 3.0.0
info:
  title: hello
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: hello
paths:
  '/user/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: 用户id
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                hello:
                  type: string
                  description: hello
components:
  schemas: {}
