openapi: 3.0.0
info:
  title: test.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: test
paths:
  /foo:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-foo
components:
  schemas: {}
